# Generated by Django 4.1.3 on 2023-09-17 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastEggDateTime', models.DateTimeField(auto_now_add=True)),
                ('LastEggQuantity', models.IntegerField(default=0)),
                ('LastEggWeight', models.IntegerField(default=0)),
                ('LastEggDuration', models.IntegerField(default=0)),
                ('NextEggDateTime', models.DateTimeField(blank=True)),
                ('CurrentEggStatus', models.BooleanField(default=False)),
                ('CurrentEggQuantity', models.IntegerField(default=0)),
                ('CurrentEggWeight', models.IntegerField(default=0)),
                ('CurrentEggDuration', models.IntegerField(default=0)),
                ('EggSystemFault', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastFeedingDateTime', models.DateTimeField(auto_now_add=True)),
                ('LastFeedWeight', models.IntegerField(default=0)),
                ('LastFeedingDuration', models.IntegerField(default=0)),
                ('NextFeedingDateTime', models.DateTimeField(blank=True)),
                ('CurrentFeedingStatus', models.BooleanField(default=False)),
                ('CurrentFeedingDuration', models.IntegerField(blank=True)),
                ('FeedingSystemFault', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WasteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastWasteDateTime', models.DateTimeField(auto_now_add=True)),
                ('LastWasteDuration', models.IntegerField(default=0)),
                ('NextWasteDateTime', models.DateTimeField(blank=True)),
                ('CurrentWasteStatus', models.BooleanField(default=False)),
                ('CurrentDuration', models.IntegerField(default=0)),
                ('WasteSystemFault', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastRefillDateTime', models.DateTimeField(auto_now_add=True)),
                ('LastRefillDuration', models.IntegerField(default=0)),
                ('CurrentRefillStatus', models.BooleanField(default=False)),
                ('WasterSystemFault', models.BooleanField(default=False)),
            ],
        ),
    ]
