# Generated by Django 4.1.3 on 2023-10-01 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autopoultryweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggcollection',
            name='CurrentEggDuration',
        ),
        migrations.RemoveField(
            model_name='eggcollection',
            name='CurrentEggQuantity',
        ),
        migrations.RemoveField(
            model_name='eggcollection',
            name='CurrentEggStatus',
        ),
        migrations.RemoveField(
            model_name='eggcollection',
            name='CurrentEggWeight',
        ),
        migrations.RemoveField(
            model_name='eggcollection',
            name='LastEggDateTime',
        ),
        migrations.RemoveField(
            model_name='eggcollection',
            name='LastEggDuration',
        ),
        migrations.RemoveField(
            model_name='eggcollection',
            name='LastEggQuantity',
        ),
        migrations.RemoveField(
            model_name='eggcollection',
            name='LastEggWeight',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='CurrentFeedingDuration',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='CurrentFeedingStatus',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='LastFeedWeight',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='LastFeedingDateTime',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='LastFeedingDuration',
        ),
        migrations.RemoveField(
            model_name='wastecollection',
            name='CurrentDuration',
        ),
        migrations.RemoveField(
            model_name='wastecollection',
            name='CurrentWasteStatus',
        ),
        migrations.RemoveField(
            model_name='wastecollection',
            name='LastWasteDateTime',
        ),
        migrations.RemoveField(
            model_name='wastecollection',
            name='LastWasteDuration',
        ),
        migrations.RemoveField(
            model_name='water',
            name='CurrentRefillStatus',
        ),
        migrations.RemoveField(
            model_name='water',
            name='LastRefillDateTime',
        ),
        migrations.RemoveField(
            model_name='water',
            name='LastRefillDuration',
        ),
        migrations.RemoveField(
            model_name='water',
            name='WasterSystemFault',
        ),
        migrations.AddField(
            model_name='eggcollection',
            name='EggDuration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='eggcollection',
            name='EggQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggcollection',
            name='EggStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eggcollection',
            name='EggWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eggcollection',
            name='StartEggDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eggcollection',
            name='StopEggDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeding',
            name='FeedWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feeding',
            name='FeedingDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feeding',
            name='FeedingStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feeding',
            name='StartFeedingDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeding',
            name='StopFeedingDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='StartWasteDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='StopWasteDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='WasteDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wastecollection',
            name='WasteStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='water',
            name='RefillDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='water',
            name='RefillStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='water',
            name='StartRefillDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water',
            name='StopRefillDateTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water',
            name='WaterSystemFault',
            field=models.BooleanField(default=False),
        ),
    ]
